### ISSUE TITLE
SPI issues on Teensy series Arduino

### ISSUE THREAD

**Issue by AirmanEpic** [Adrien-Legrand/AS5X47#1] opened 2020-11-22 02:44 UTC
Unfortunately it seems as though the teensy series controllers do not have the ability to use this library properly or the library does not use the teensy SPI system properly. 

while using the readangle example files on both teensy 4.0 and 3.6, for a variety of CPU speeds, the output is 0 for any values of rotation. SPI bus is plugged in correctly with all pins in the correct ports.

If purchasing components is necessary to fix this issue, please write me a bill.

**Comment by Adrien-Legrand** [comment] 2020-11-22 20:00
I just reviewed the teensy SPI implementation. It seems fully compatible with the AS5X47 library.
The SPI clock configuration is made here : 

- [Reading](https://github.com/Adrien-Legrand/AS5X47/blob/8ae89fec7b8b16b59b98aa63822aca21831992fb/src/AS5X47Spi/AS5X47Spi.cpp#L58)
- [Writing](https://github.com/Adrien-Legrand/AS5X47/blob/8ae89fec7b8b16b59b98aa63822aca21831992fb/src/AS5X47Spi/AS5X47Spi.cpp#L43)

`SPISettings(100000, MSBFIRST, SPI_MODE1)`

The maximum SPI frequency is set very low (100kHz) but that should not be an issue. 
According to the SPI library references, the chosen frequency is the greatest clock frequency lower or equal to the specified value. If no clock has a frequency lower than the specified one, the lowest available is used.

In the case of an Arduino Uno or a Teensy, the lowest clock frequency available is chosen because there is no clock as low as 100kHz.

However, it is a good idea to expose this parameter and let the opportunity for the user to use a custom one.

If you want to test changing the frequency, you can edit the file **AS5X47Spi.cpp** in your Arduino library folder. Let me know if you have results. I will acquire a Teensy 4.0 board to run some tests here and see if I can reproduce the issue.

**Comment by AirmanEpic** [comment] 2020-11-23 00:27
I am afraid I have tried many clock speeds, varying them up and down by as much as 3 orders of magnitude to see which would work, to no success.
null

**Comment by Adrien-Legrand** [comment] 2020-11-23 17:43
It seems to be a hardware issue. Have you tried the same sensor with the same cables connected to an Arduino, in order to check if the issue is not from the sensor or a cable itself ?

Do you have to possibility to monitor the signals at MOSI and MISO pins with an oscilloscope ?

**Comment by AirmanEpic** [comment] 2020-11-23 21:43
I have checked with an Arduino uno, using your code, and had no issues.

However, I do not have an o-scope so I cannot check pins.

**Comment by Adrien-Legrand** [comment] 2020-12-02 21:55
Hi, 
I made some updates, can you please try to install the following alpha version of the library and tell me if it is better ?
I had great results here.

1. [Go to this commit page and download zip file ('Code Button' -> 'Download ZIP')](https://github.com/Adrien-Legrand/AS5X47/tree/7bf1077ed03e14949522864880f957bfb19d424f)
2. Go to your Arduino folder (for Windows in <My Documents>/Arduino/libraries)
3. Remove AS5X47-1.0.0 folder
4. Copy AS5X47 folder from ZIP file here.
5. Recompile the example and test it.

Let me know if you have good results so I can release a new version of the library.

**Comment by AirmanEpic** [comment] 2020-12-09 03:36
I'm afraid not. Tested on Teensy 4.0 and 3.6 with a variety of clock speeds and still no results.

**Comment by AirmanEpic** [comment] 2020-12-09 03:37
I begin to wonder if I installed the library properly but it seems very straightforward. I did unzip the folder first and rename it to AS5X47 instead of including the commit code behind it.

**Comment by Adrien-Legrand** [comment] 2020-12-11 18:29
Please ensure that you downloaded and installed the correct version : 

- Open the following file in your library folder :  **<AS5X47>/src/AS5X47Spi/AS5X47Spi.cpp**
- Ensure that the line `delayMicroseconds(1);` is present in both writeData and readData methods.

**Comment by AirmanEpic** [comment] 2020-12-11 18:42
It is present.

https://i.gyazo.com/a00f24f1137f0a52da5652e8a8bc8c04.png

I have attempted a similar technique and not had any luck. Thank you for continuing to work on this.

Perhaps the problem is with my specific hardware, though it's odd that it persists across two different boards.

**Comment by Adrien-Legrand** [comment] 2020-12-11 18:56
With the previous version of the library, there was no delay between two SPI communications and thus bewteen the ChipSelect signal level changes. With an Arduino it is not an issue because of the clock frequency relatively low. But with the Teensy clock frequency, the AS5147 sensor was not able to detect the changes.

Adding the delay is sufficient to establish the communication between the Teensy 4.0 and the custom AS5147P board I have.

Thus, I now suspect a hardware issue :  do you have any other SPI device to test if the teensy SPI still working ?

**Comment by AirmanEpic** [comment] 2020-12-11 21:03
I'm afraid I do not. And it may well be that problem. I may be not configuring the teensy's SPI properly too.

**Comment by Adrien-Legrand** [comment] 2020-12-12 11:14
As the ReadAngle example is working for me with a Teensy 4.0, the problem is not from the library, I can't do more for you.
I will close the issue and update the library version with the delay modification.
I hope you find a solution for your application.

**Closed as completed by Adrien-Legrand** 2020-12-12 11:14 UTC
